version: '3.1'

services:
  grafana-server:
    image: "bitnami/grafana:10.0.2"
    container_name: "grafana"
    volumes:
      - ./conf/grafana.ini:/opt/bitnami/grafana/conf/grafana.ini
      - ./data/grafana_data:/opt/bitnami/grafana/data
    ports:
      - '3000:3000'
    networks:
      - grafana
    restart: on-failure

networks:
  grafana:
    driver: bridge
