apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
spec:
  selector:
    component: etcd
  ports:
  - port: 2379
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-deploy
spec:
  selector:
    matchLabels:
      component: etcd
  template:
    metadata:
      labels:
        component: etcd
    spec:
      containers:
      - name: redis
        image: docker.io/bitnami/etcd:3.4.13
        ports:
        - containerPort: 2379
        env:
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
