version: '3.1'
services:
  easyconnect:
    image: hagb/docker-easyconnect:7.6.7
    container_name: easyconnect
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    command:
    environment:
      PASSWORD: xxxx
      URLWIN: "1"
    ports:
      # vnc client link port
      - "5901:5901"
      # socket proxy port
      - "7891:1080"
      # http proxy port
      - "7890:8888"
    volumes:
      - $HOME/.ecdata:/root
    restart: on-failure
