version: '3'
services:
  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
    privileged: true
    restart: on-failure
