version: '3'
services:
  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "18080:80"
    privileged: true
    restart: on-failure
