version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.50
    ports:
    - "6831:6831/udp" # accept jaeger.thrift over Thrift-compact protocol (used by most SDKs)
    - "6832:6832/udp" # accept jaeger.thrift over Thrift-binary protocol (used by Node.js SDK)
    - "5778:5778" # serve configs (sampling, etc.)
    - "16686:16686" # serve frontend
    - "4317:4317" # accept OpenTelemetry Protocol (OTLP) over gRPC
    - "4318:4318" # accept OpenTelemetry Protocol (OTLP) over HTTP
    - "14250:14250" # accept model.proto
    - "14268:14268" # accept jaeger.thrift directly from clients
    - "14269:14269" # 
    - "9411:9411" # Zipkin compatible endpoint (optional)
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    restart: on-failure
