version: '2'
services:
  minio:
    image: docker.io/bitnami/minio:2021
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ACCESS_KEY: 'minio-access-key'
      MINIO_SECRET_KEY: 'minio-secret-key'
      MINIO_DEFAULT_BUCKETS: 'test-buckets'
volumes:
  minio_data:
    driver: local
