version: '3.1'

services:
  prometheus-server:
    image: bitnami/prometheus:2.23.0
    container_name: prometheus-server
    volumes:
      # https://prometheus.io/docs/prometheus/latest/configuration/configuration
      - ./conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./data/prometheus_data:/opt/bitnami/prometheus/data
    command:
      - "--config.file=/opt/bitnami/prometheus/conf/prometheus.yml"
      - "--storage.tsdb.path=/opt/bitnami/prometheus/data"
      - "--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries"
      - "--web.console.templates=/opt/bitnami/prometheus/conf/consoles"
      - "--web.route-prefix=/"
    ports:
      - '9090:9090'
    networks:
      - prometheus
    restart: on-failure

networks:
  prometheus:
    driver: bridge
