version: '3.1'
services:
  prometheus-server:
    image: bitnami/prometheus:2.23.0
    container_name: prometheus-server
    volumes:
      # https://prometheus.io/docs/prometheus/latest/configuration/configuration
      - ./conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./data/prometheus_data:/opt/bitnami/prometheus/data
    command:
      - "--config.file=/opt/bitnami/prometheus/conf/prometheus.yml"
      - "--storage.tsdb.path=/opt/bitnami/prometheus/data"
      - "--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries"
      - "--web.console.templates=/opt/bitnami/prometheus/conf/consoles"
      - "--web.route-prefix=/"
    ports:
      - '9090:9090'
    restart: on-failure

  grafana-server:
    image: bitnami/grafana:7.3.4
    container_name: grafana-server
    environment:
      # https://grafana.com/docs/grafana/latest/administration/configuration/
      - 'GF_SECURITY_ADMIN_USER=admin'
      - 'GF_SECURITY_ADMIN_PASSWORD=admin_password'
      # https://grafana.com/tutorials/run-grafana-behind-a-proxy/
      - 'GF_SERVER_HTTP_PORT=8848'
      - 'GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/'
      - 'GF_SERVER_SERVE_FROM_SUB_PATH=true'
    volumes:
      - ./data/grafana_data:/opt/bitnami/grafana/data
    ports:
      - '8848:8848'
    restart: on-failure

