version: "3.9"
services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v4.1.3
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "8100:8000"
      - "8101:9000"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
