apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx 
  ports:
  - port: 80
    protocol: TCP

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18.0-alpine
        ports:
        - containerPort: 80
