version: '3.1'
services:
  redis:
    image: redis/redis-stack:7.2.0-v8
    volumes:
      - ./data:/data
    environment:
      - REDIS_ARGS="--requirepass redispw"
    ports:
      - "16379:6379"
      - "8001:8001"
    restart: on-failure
