version: "3.1"
services:
  etcd:
    image: docker.io/bitnami/etcd:3.5.7
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    volumes:
      - ./data/etcd_data:/bitnami/etcd
    networks:
      - apisix
    restart: on-failure

  apisix:
    image: apache/apisix:3.4.0-debian
    volumes:
      - ./conf/apisix-config.yaml:/usr/local/apisix/conf/config.yaml
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      - apisix
    restart: on-failure

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    volumes:
      - ./conf/dashboard-config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000/tcp"
    networks:
      - apisix
    restart: on-failure

  prometheus:
    image: bitnami/prometheus:2.23.0
    volumes:
      # https://prometheus.io/docs/prometheus/latest/configuration/configuration
      - ./conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./data/prometheus_data:/opt/bitnami/prometheus/data
    command:
      - "--config.file=/opt/bitnami/prometheus/conf/prometheus.yml"
      - "--storage.tsdb.path=/opt/bitnami/prometheus/data"
      - "--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries"
      - "--web.console.templates=/opt/bitnami/prometheus/conf/consoles"
      - "--web.route-prefix=/"
    networks:
      - apisix
    restart: on-failure

  grafana:
    image: "bitnami/grafana:10.0.2"
    container_name: "grafana"
    volumes:
      - ./conf/grafana.ini:/opt/bitnami/grafana/conf/grafana.ini
      - ./data/grafana_data:/opt/bitnami/grafana/data
    ports:
      - '3000:3000'
    networks:
      - apisix
    restart: on-failure

networks:
  apisix:
    driver: bridge

