apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager-example
spec:
  replicas: 1
  alertmanagerConfigSelector:
    matchLabels:
      alert-manager-config-instance: 'alert-manager-config-example'

