version: '3.1'
services:
  buildkitd:
    image: moby/buildkit:latest
    command: 
    - "--addr=tcp://0.0.0.0:1234"
    ports:
    - "1234:1234"
    container_name: buildkitd
    privileged: true
    restart: on-failure
