version: '3.1'
services:
  redis:
    image: 'bitnami/redis:6.2.12'
    restart: on-failure
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "./data/master:/bitnami/redis/data"
    networks:
      - tier
    
  redis-slave:
    image: 'bitnami/redis:6.2.12'
    restart: on-failure
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "./data/slave:/bitnami/redis/data"
    depends_on:
      - redis
    networks:
      - tier

  redis-sentinel:
    image: 'bitnami/redis-sentinel:6.2.12'
    restart: on-failure
    volumes:
      - "./data/sentinel:/bitnami/redis/data"
    depends_on:
      - redis
      - redis-slave
    networks:
      - tier

networks:
  tier:
    driver: bridge
