apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    component: redis
  ports:
  - port: 6379
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:6-alpine3.12
        ports:
        - containerPort: 6379
