version: '3.1'
services:
  redis:
    image: bitnami/redis:6.2.12
    volumes:
      - ./data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_PASSWORD=password
      #- REDIS_AOF_ENABLED=no
    ports:
      - "6379:6379"
    restart: on-failure
