version: '3.1'
services:
  mysql:
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "13306:3306"
    volumes:
      - ./data:/var/lib/mysql
