apiVersion: v1
kind: Service
metadata:
  name: redis-stack
spec:
  selector:
    app: redis-stack
  ports:
  - port: 6379
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack
spec:
  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      containers:
      - name: redis
        image: redis/redis-stack:latest
        ports:
        - containerPort: 6379
