version: '2'
services:
  etcd:
    image: docker.io/bitnami/etcd:3.4.13
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./data:/bitnami/etcd
    ports:
      - "2379:2379"
    restart: on-failure
