global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.41.1.140:9090']

  - job_name: 'open-match-mmf'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.41.1.140:51509']

  - job_name: 'open-match-evaluator'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.41.1.140:51508']

  - job_name: 'open-match-synchronizer'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.41.1.140:51506']

  - job_name: 'open-match-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.41.1.140:51505']

  - job_name: 'open-match-frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.41.1.140:51504']

  - job_name: 'open-match-query'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.41.1.140:51503']

